# search for a safe spot before teleporting
safe_teleport: true

# max tries to find a safe spot
max_tries: 10

# can be "vanilla" or "plugin"
border_mode: "vanilla"

cooldown: 10

# deny teleporting to the following blocks
unsafe_blocks:
  - "BEDROCK"
  - "FIRE"
  - "LAVA"
  - "MAGMA"
  - "WATER"
  - "STATIONARY_WATER"
  - "SIGN"
  - "SIGN_POST"
  - "WALL_SIGN"
  - "VINE"
  - "STRING"
  - "GOLD_PLATE"
  - "IRON_PLATE"
  - "STONE_PLATE"
  - "WOOD_PLATE"
  - "FENCE_GATE"
  - "PORTAL"
  - "ENDER_PORTAL"