safe-teleport: true
cooldown: 10
max-tries: 10
max-vanilla-radius: 4096
unsafe-blocks:
  - "BEDROCK"
  - "FIRE"
  - "LAVA"
  - "MAGMA"
  - "WATER"
  - "STATIONARY_WATER"
  - "SIGN"
  - "SIGN_POST"
  - "WALL_SIGN"
  - "VINE"
  - "STRING"
  - "GOLD_PLATE"
  - "IRON_PLATE"
  - "STONE_PLATE"
  - "WOOD_PLATE"
  - "FENCE_GATE"
  - "PORTAL"
  - "ENDER_PORTAL"
messages:
  teleport-success: "&aDu wurdest $distanceTeleported Blöcke weit weg teleportiert"
  safespot-not-found: "&cEin sicherer Ort konnte leider nicht gefunden werden :("
  cooldown: "&cDu darfst dich nur alle $cooldown Sekunden teleportieren. Versuche es in $timeLeft Sekunden noch einmal"
