# search for a safe spot before teleporting
safe_teleport: false

# max tries to find a safe spot
max_tries: 10

# can be "vanilla" or "plugin"
border_mode: "vanilla"

# deny teleporting to the following blocks
unsafe_blocks:
  - "LAVA"
  - "WATER"
  - "STATIONARY_WATER"