# search for a safe spot before teleporting
safe_teleport: true

# max tries to find a safe spot
max_tries: 10

# can be "vanilla" or "plugin"
border_mode: "plugin"

# deny teleporting to the following blocks
unsafe_blocks:
  - "BEDROCK"
  - "FIRE"
  - "LAVA"
  - "MAGMA_BLOCK"
  - "WATER"
  - "SIGN"
  - "WALL_SIGN"
  - "VINE"
  - "STRING"
  - "HEAVY_WEIGHTED_PRESSURE_PLATE"
  - "LIGHT_WEIGHTED_PRESSURE_PLATE"
  - "ACACIA_PRESSURE_PLATE"
  - "BIRCH_PRESSURE_PLATE"
  - "DARK_OAK_PRESSURE_PLATE"
  - "JUNGLE_PRESSURE_PLATE"
  - "OAK_PRESSURE_PLATE"
  - "SPRUCE_PRESSURE_PLATE"
  - "STONE_PRESSURE_PLATE"
  - "NETHER_PORTAL"
  - "END_PORTAL"