# Plugin info
api-version: "1.12"
name: "RandomTeleport"
description: "${project.description}"
version: "${project.version}"
main: "io.github.twieteddy.randomteleport.RandomTeleportPlugin"
database: false
depend: []
softdepend: ["WorldBorder"]

# Authors
author: "Teddy"
authors: []
website: "https://twieteddy.github.io"

permissions:
  randomteleport.command.rtp:
    default: op
  randomteleport.cooldown.bypass:
    default: op

commands:
  rtp:
    description: Teleports you to a random location inside the worldborder
    permission: randomteleport.command.rtp
    aliases: []