name: RandomTeleport
version: "2.0"
api-version: "1.13"
description: "RandomTeleport"

author: Teddy
authors: []
website: https://twieteddy.github.io

main: io.github.twieteddy.randomteleport.RandomTeleport
database: false
depend: []
softdepend: [WorldBorder]

permissions:
  randomteleport.command.rtp:
    default: op

commands:
  rtp:
    description: Teleports you to a random location inside the worldborder
    permission: randomteleport.command.rtp
    aliases: []